name: pml_fe
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  audioplayers: ^6.3.0
  confetti: ^0.8.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_tts: ^4.2.2
  go_router: ^14.8.1
  http: ^1.3.0
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2
  speech_to_text: ^7.0.0
  lottie: ^3.3.1
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  flip_card: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/alarm.wav
    - assets/animations/
    - assets/images/
    - .env
